[osonpos]
user = __PROJECT_OWNER__
group = __PROJECT_OWNER__

listen = /run/php/php8.4-fpm-osonpos.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = ondemand
pm.max_children = 8
pm.process_idle_timeout = 10s
pm.max_requests = 500

chdir = /
